# Generated by Django 6.0 on 2025-12-27 09:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=200)),
                (
                    "food_type",
                    models.CharField(
                        choices=[("veg", "Vegetarian"), ("non-veg", "Non-Vegetarian")],
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "prepared_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "expiry_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 12, 28, 9, 59, 51, 51004, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("pickup_location", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("donated", "Donated"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
