# Generated by Django 6.0 on 2025-12-27 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0002_alter_foodlisting_expiry_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 10, 39, 0, 593963, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
