# Generated by Django 6.0 on 2025-12-27 11:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0003_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodrequest",
            name="contact_person",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="pickup_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="vehicle_info",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 11, 59, 39, 174135, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="foodrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
