# Generated by Django 6.0 on 2025-12-27 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0004_foodrequest_contact_person_foodrequest_pickup_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodlisting",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="foodlisting",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 14, 30, 52, 604890, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
