# Generated by Django 6.0 on 2025-12-27 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0005_alter_foodlisting_options_foodlisting_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 28, 15, 7, 5, 296128, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
