# Generated by Django 6.0 on 2025-12-28 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0006_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 29, 6, 41, 20, 759553, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
