# Generated by Django 6.0 on 2025-12-29 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0007_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlisting",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodlisting",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 30, 15, 56, 56, 189169, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
