# Generated by Django 6.0 on 2025-12-29 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0008_foodlisting_latitude_foodlisting_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 12, 30, 16, 5, 1, 131742, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
