# Generated by Django 6.0 on 2025-12-31 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0009_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 1, 12, 57, 31, 443625, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
