# Generated by Django 6.0 on 2025-12-31 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0010_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 1, 13, 20, 25, 308345, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
