# Generated by Django 6.0 on 2025-12-31 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0011_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 1, 13, 22, 16, 341207, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
