# Generated by Django 6.0 on 2026-01-01 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0012_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 2, 4, 42, 29, 920938, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
