# Generated by Django 6.0 on 2026-01-06 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0014_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodrequest",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 7, 4, 56, 50, 69497, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
