# Generated by Django 6.0 on 2026-01-06 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0015_foodrequest_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 7, 14, 38, 23, 481073, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
