# Generated by Django 6.0 on 2026-01-06 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0016_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 7, 14, 50, 37, 39027, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
