# Generated by Django 6.0 on 2026-01-07 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0018_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 8, 3, 42, 22, 187868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
