# Generated by Django 6.0 on 2026-01-11 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0019_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 12, 7, 16, 57, 302976, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
