# Generated by Django 6.0 on 2026-01-11 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0020_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 12, 9, 8, 14, 301375, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
