# Generated by Django 6.0 on 2026-01-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0022_create_donor_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 22, 7, 4, 52, 849992, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
