# Generated by Django 6.0 on 2026-01-21 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0023_alter_donorreport_id_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 1, 22, 7, 30, 5, 404160, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
