# Generated by Django 4.2.11 on 2026-01-24 01:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0024_alter_foodlisting_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 1, 47, 20, 709731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='foodrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_request', 'New Food Request'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('request_completed', 'Request Completed'), ('food_expiring', 'Food Expiring Soon')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donor.foodrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
