# Generated by Django 6.0.3 on 2026-07-01 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0026_alter_donorreport_id_alter_foodlisting_expiry_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 2, 12, 15, 1, 988301, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
