# Generated by Django 6.0.3 on 2026-07-01 13:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0027_alter_foodlisting_expiry_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="foodrequest",
            name="delivery_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="delivery_proofs/"
            ),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("none", "No Delivery Needed"),
                    ("pending_driver", "Awaiting Driver"),
                    ("accepted", "Accepted by Driver"),
                    ("picked_up", "Picked Up"),
                    ("delivered", "Delivered"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driver_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 2, 13, 58, 36, 407586, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
