# Generated by Django 6.0.3 on 2026-07-03 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0028_foodrequest_delivery_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 4, 7, 45, 2, 71065, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
