# Generated by Django 6.0.3 on 2026-07-07 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0029_alter_foodlisting_expiry_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-priority_score", "-created_at"]},
        ),
        migrations.AddField(
            model_name="notification",
            name="priority_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 8, 8, 15, 5, 293872, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
