# Generated by Django 6.0.3 on 2026-07-07 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor", "0030_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlisting",
            name="ambient_temperature",
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name="foodlisting",
            name="ml_category",
            field=models.CharField(default="veg", max_length=20),
        ),
        migrations.AddField(
            model_name="foodlisting",
            name="packaging_type",
            field=models.CharField(default="boxed", max_length=20),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="transit_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodrequest",
            name="transit_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="foodlisting",
            name="expiry_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 7, 8, 8, 18, 32, 757240, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
