# Generated by Django 6.0 on 2026-01-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("organization_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant / Hotel"),
                            ("manufacturer", "Food Manufacturer"),
                            ("distributor", "Distributor / Warehouse"),
                            ("nonprofit", "Nonprofit / NGO"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "donation_size",
                    models.CharField(
                        choices=[
                            ("small", "Small (occasional surplus)"),
                            ("medium", "Medium (regular donations)"),
                            ("large", "Large (bulk / palletized donations)"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
