# Generated by Django 6.0 on 2025-12-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20251227_1939"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="activitylog",
            table=None,
        ),
    ]
