# Generated by Django 6.0 on 2025-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_activitylog_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
