# Generated by Django 6.0 on 2025-12-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="license_document",
            field=models.FileField(
                blank=True,
                help_text="Upload government verified license (PDF only)",
                null=True,
                upload_to="licenses/",
            ),
        ),
    ]
