# Generated by Django 6.0.3 on 2026-07-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_activitylog_id_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Description of the organization's mission",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_freezer",
            field=models.BooleanField(
                default=False, help_text="Has freezer storage capability"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_fridge",
            field=models.BooleanField(
                default=False, help_text="Has cold storage capability"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_warmers",
            field=models.BooleanField(
                default=False, help_text="Has hot holding capability"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="max_capacity",
            field=models.IntegerField(
                default=100, help_text="Maximum distribution capacity (servings)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="vehicle_capacity",
            field=models.IntegerField(
                default=0, help_text="Maximum servings capacity for vehicle transport"
            ),
        ),
    ]
