# Generated by Django 6.0.3 on 2026-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_profile_bio_profile_has_freezer_profile_has_fridge_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("donor", "Donor"),
                    ("receiver", "Receiver"),
                    ("driver", "Volunteer Logistics Driver"),
                    ("admin", "Admin"),
                ],
                default="donor",
                max_length=10,
            ),
        ),
    ]
