# Generated by Django 6.0.3 on 2026-07-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="aadhaar_card",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_driver_onboarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="vehicle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="vehicle_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
